[green_agent]
agentbeats_id = "019b4dfd-a332-7a13-8887-d519a8430043"
image = "ghcr.io/li-yueting/agentbeats-tutorial-personagym-evaluator:latest"
env = { OPENAI_API_KEY = "${OPENAI_API_KEY}" }

[[participants]]
agentbeats_id = "019b4df5-9e7d-7b01-b8d0-c36d868f1540"
name = "agent"
image = "ghcr.io/li-yueting/agentbeats-tutorial-personagym-agent:latest"
env = { OPENAI_API_KEY = "${OPENAI_API_KEY}" }

[config]
domain = "airline"
num_rounds = 3
